export const ROUTES = {
  HOME: '/',
  AUTH: {
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
  },
  DASHBOARD: {
    HOME: '/dashboard',
  },
  PRODUCTS: {
    LIST: '/products',
    DETAIL: (id) => `/products/${id}`,
    SEARCH: '/search',
    BY_BRAND: (brand) => `/products?brand=${encodeURIComponent(brand)}`,
    BY_CATEGORY: (category) => `/products?category=${encodeURIComponent(category)}`,
    BY_COLLECTION: (collection) => `/search?q=${encodeURIComponent(collection)}&type=collection`,
  },
  WISHLIST: '/wishlist',
  CART: '/cart',
  CHECKOUT: '/checkout',
  ORDERS: '/orders',
  ORDERS_BY_ID: (id) => `/orders/${id}`,
  MY_CLOSET: '/my-closet',
  MY_CLOSET_SECTION: (section) => `/my-closet/${section}`,
  PROFILE: {
    HOME: '/profile',
    SETTINGS: '/profile/settings',
  },
  AI: {
    RECOMMENDATIONS: '/recommendations',
    FASHION_DNA: '/fashion-dna',
    STYLIST: '/stylist',
    VIRTUAL_TRY_ON: '/virtual-try-on',
  },
  FACE: {
    REGISTER: '/face/register',
    LOGIN: '/face/login',
    ANALYSIS: '/face-analysis',
  },
  BODY: {
    ANALYSIS: '/body-analysis',
  },
  AVATAR: {
    HOME: '/digital-avatar',
  },
  ONBOARDING: {
    PROFILE: '/onboarding/profile',
    LIFESTYLE: '/onboarding/lifestyle',
    STYLE: '/onboarding/style',
  },
  ADMIN: {
    HOME: '/admin',
    DASHBOARD: '/admin/dashboard',
    USERS: '/admin/users',
    PRODUCTS: '/admin/products',
    ANALYTICS: '/admin/analytics',
    ANALYTICS_REVENUE: '/admin/analytics/revenue',
    ANALYTICS_USERS: '/admin/analytics/users',
    ANALYTICS_CONVERSION: '/admin/analytics/conversion',
    ANALYTICS_CUSTOMERS: '/admin/analytics/customers',
    ANALYTICS_PRODUCTS: '/admin/analytics/products',
    ANALYTICS_USER_GROWTH: '/admin/analytics/user-growth',
    ANALYTICS_DEVICES: '/admin/analytics/devices',
    ANALYTICS_ORDERS: '/admin/analytics/orders',
    ANALYTICS_CATEGORIES: '/admin/analytics/categories',
    ORDERS: '/admin/orders',
    ORDERS_ANALYTICS: '/admin/orders/analytics',
    SUPPORT: '/admin/support',
    PROFILE: '/admin/profile',
  },
  SUPPORT: {
    HOME: '/support',
    NEW: '/support/new',
    TICKETS: '/support/tickets',
    TICKET: (id) => `/support/tickets/${id}`,
  },
};

export const PUBLIC_ROUTES = [
  ROUTES.HOME,
  ROUTES.AUTH.LOGIN,
  ROUTES.AUTH.REGISTER,
  ROUTES.AUTH.FORGOT_PASSWORD,
  ROUTES.FACE.LOGIN,
];

export const PROTECTED_ROUTES = [
  ROUTES.DASHBOARD.HOME,
  ROUTES.PROFILE.HOME,
  ROUTES.PRODUCTS.LIST,
  ROUTES.PRODUCTS.SEARCH,
  ROUTES.WISHLIST,
  ROUTES.CART,
  ROUTES.CHECKOUT,
  ROUTES.ORDERS,
  ROUTES.MY_CLOSET,
  ROUTES.AI.RECOMMENDATIONS,
  ROUTES.AI.STYLIST,
  ROUTES.AI.VIRTUAL_TRY_ON,
  ROUTES.AI.FASHION_DNA,
  ROUTES.FACE.ANALYSIS,
  ROUTES.BODY.ANALYSIS,
  ROUTES.AVATAR.HOME,
  ROUTES.ONBOARDING.PROFILE,
  ROUTES.ONBOARDING.LIFESTYLE,
  ROUTES.ONBOARDING.STYLE,
  ROUTES.SUPPORT.HOME,
  ROUTES.SUPPORT.TICKETS,
];
