export function isFormattedAvatarOutfit(outfit) {
  return Boolean(
    outfit
    && ('selectedTshirtId' in outfit
      || 'selectedShirtId' in outfit
      || 'selectedJacketId' in outfit),
  );
}

export function formatAvatarRecord(avatar, outfit = null, metadata = {}) {
  if (!avatar) {
    return null;
  }

  const formattedOutfit = outfit
    ? (isFormattedAvatarOutfit(outfit)
      ? outfit
      : formatAvatarOutfitRecord(outfit, outfit.products || {}))
    : null;

  return {
    id: avatar.id,
    userId: avatar.user_id,
    bodyType: avatar.body_type,
    skinTone: avatar.skin_tone,
    hairColor: avatar.hair_color,
    baseAvatarUrl: avatar.base_avatar_url,
    model3dUrl: avatar.model_3d_url,
    avaturnAvatarId: metadata.avaturnAvatarId ?? null,
    rpmAvatarId: metadata.rpmAvatarId ?? null,
    hasCustom3dAvatar: metadata.hasCustom3dAvatar ?? false,
    hasReadyPlayerMeAvatar: metadata.hasReadyPlayerMeAvatar ?? false,
    generationProfile: metadata.generationProfile ?? null,
    rpmEditorConfig: metadata.rpmEditorConfig ?? null,
    stylePreferences: metadata.stylePreferences ?? null,
    traitSources: metadata.traitSources ?? null,
    wasAutoGenerated: metadata.wasAutoGenerated ?? false,
    createdAt: avatar.created_at,
    updatedAt: avatar.updated_at,
    outfit: formattedOutfit,
  };
}

export function formatAvatarOutfitRecord(outfit, products = {}) {
  if (!outfit) {
    return null;
  }

  return {
    id: outfit.id,
    avatarId: outfit.avatar_id,
    selectedTshirtId: outfit.selected_tshirt_id,
    selectedShirtId: outfit.selected_shirt_id,
    selectedJacketId: outfit.selected_jacket_id,
    selectedPantId: outfit.selected_pant_id,
    selectedShoesId: outfit.selected_shoes_id,
    totalPrice: outfit.total_price,
    products,
    updatedAt: outfit.updated_at,
  };
}

export function formatAvatarVersionRecord(version) {
  return {
    id: version.id,
    avatarId: version.avatar_id,
    versionName: version.version_name,
    imageUrl: version.image_url,
    createdAt: version.created_at,
  };
}
